name: yandex_mapkit_lite
description: This is a lightweight fork of the yandex_mapkit package version 3.4.0.
version: 2.0.0
homepage: https://github.com/surfstudio/yandex-mapkit-lite-flutter

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter_plugin_android_lifecycle: ^2.0.15
  equatable: ^2.0.5
  collection: ^1.17.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.unact.yandexmapkit
        pluginClass: YandexMapkitPlugin
      ios:
        pluginClass: YandexMapkitPlugin
